//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Constants
	{
		public static string GAME_NAME = "2Pac";
		public static Random random = new Random();
		public static IntVector2[] directions = new IntVector2[]{new IntVector2(1,0), new IntVector2(0,1), new IntVector2(-1,0), new IntVector2(0,-1)};
		public static readonly int BoardCellRadius = 1000;
		public static readonly int BoardCellDiameter = 2000;
		public static readonly float PelletWorth = 10f;
		public static readonly float PowerPelletTime = 5f;
		public static readonly int GhostWorth = 100;
		
		private Constants ()
		{
		}
	}
}

