//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class GhostAIFactory
	{
		private PacmanData[] Players;
		private BoardAccessor Accessor;

		public GhostAIFactory( PacmanData[] players, BoardAccessor Accessor )
		{
			this.Players = players;
			this.Accessor = Accessor;
		}

		public GhostAI getGhostByNumber( int num, GhostData Data )
		{
			if ( num == 0 )
			{
				return new BlinkyAI( Players, Accessor, Data );
			}
			else if ( num == 1 )
			{
				return new PinkyAI( Players, Accessor, Data );
			}
			else if ( num == 2 )
			{
				return new InkyAI( Players, Accessor, Data );
			}
			else if ( num == 3 ){
				return new ClydeAI( Players, Accessor, Data );
			}
			else
			{
				throw new NotImplementedException();
			}

		}

	}
}

