//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
namespace AssemblyCSharp
{
	public class GameBoard
	{
		public bool[,] board;

		public GameBoard (bool[,] board)
		{
			this.board = board;
		}

		public Vector2 tryMove( Vector3 pos, Vector2 vel )
		{
			int x = (int)pos.x;
			int y = (int)pos.y;
			
			float cellPosX = pos.x - x - .5f;
			float cellPosY = pos.y - y - .5f;

			cellPosX += vel.x;
			cellPosY += vel.y;

			bool[] roads = new bool[4]{ x < board.GetLength(1) - 1 && !board[y, x+1], 
				                        y < board.GetLength(0) - 1 && !board[y+1,x], 
				                        x > 0 && !board[y,x-1], 
				                        y > 0 && !board[y-1,x]};
			
			if ( cellPosX > 0 && !roads[0] ) cellPosX = 0;
			if ( cellPosX < 0 && !roads[2] ) cellPosX = 0;
			if ( cellPosY > 0 && !roads[1] ) cellPosY = 0;
			if ( cellPosY < 0 && !roads[3] ) cellPosY = 0;


			if ( Math.Abs( cellPosX ) > Math.Abs( cellPosY ) ) cellPosY = 0;
			else cellPosX = 0;

			if ( x <= 0 || board[y, x-1] ) cellPosX = Math.Max( cellPosX, 0 );
			if ( y <= 0 || board[y-1, x] ) cellPosY = Math.Max( cellPosY, 0 );
			if ( x >= board.GetLength(1) - 1 || board[y, x+1] ) cellPosX = Math.Min( cellPosX, 0 );
			if ( y >= board.GetLength(0) || board[y + 1, x] ) cellPosY = Math.Min( cellPosY, 0 );
			
			return new Vector3( cellPosX + x + .5f, cellPosY + y + .5f, 0 );

		}


	}
}

