//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class IntVector2
	{
		public int x {get; private set;}
		public int y {get; private set;}
		public IntVector2 (int x, int y)
		{
			this.x = x;
			this.y = y;
		}

		public override int GetHashCode ()
		{
			// 6571 is a "big" prime
			return x * 6571 + y;
		}

		public override bool Equals (object obj)
		{
			IntVector2 o = obj as IntVector2;
			if ( o != null && o.x == x && o.y == y ) return true;
			return base.Equals( obj );
		}

		public static IntVector2 operator +( IntVector2 a, IntVector2 b )
		{
			return new IntVector2( a.x + b.x, a.y + b.y );
		}

	}
}

